# Configuration for fine-tuning Qwen 2.5 VL on healthcare activity recognition dataset

### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 65536  # Increased for better video resolution
trust_remote_code: true

### logging
report_to: wandb
logging_steps: 10
run_name: qwen25vl-healthcare-activity

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
freeze_vision_tower: true  # Freeze vision tower to save memory
freeze_multi_modal_projector: false  # Unfreeze projector for better cross-modal alignment
freeze_language_model: true  # Freeze language model when using LoRA
# device_map: auto  # Automatically distribute across available GPUs
# auto_find_batch_size: true  # Automatically find workable batch size

### dataset
dataset_dir: /home/mukul.ranjan/projects/video-vlm/LLaMA-Factory/data
dataset: healthcare_activity
template: qwen2_vl
media_dir: /l/users/mukul.ranjan/video_data/activity_clips/activity_clips
cutoff_len: 2048
max_samples: 3000  # Limit samples to avoid overfitting
overwrite_cache: true
preprocessing_num_workers: 8  # Reduced from 16 to avoid memory issues
dataloader_num_workers: 4

### output
output_dir: /home/mukul.ranjan/projects/video-vlm/qwen25vl_activity_finetuning/output

### training stability
gradient_checkpointing: true
gradient_accumulation_steps: 2  # Increased to reduce memory pressure
per_device_train_batch_size: 1
evaluation_strategy: steps
eval_steps: 200
save_strategy: steps
save_steps: 500
save_total_limit: 3
ddp_find_unused_parameters: false
logging_steps: 10
low_cpu_mem_usage: true  # Optimize memory usage
plot_loss: true
overwrite_output_dir: true
save_only_model: false
auto_find_batch_size: true  # Allow automatic batch size finding

### train
# per_device_train_batch_size already defined above as 1
# gradient_accumulation_steps already defined above as 8
learning_rate: 2.0e-5  # Slightly higher learning rate
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
